# Generated by Django 4.2.3 on 2023-08-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
    ]
